name: Package

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: package-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  arch:
    uses: MasonRhodesDev/packaging-workflows/.github/workflows/arch-package.yml@a1b85c42addd5e876f301886f5c6ea9d1cc9b168

  rpm:
    uses: MasonRhodesDev/packaging-workflows/.github/workflows/rpm-check.yml@a1b85c42addd5e876f301886f5c6ea9d1cc9b168
    with:
      spec-name: hyprstate
